---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    # Check for updates once a day
    schedule:
      interval: daily
  - package-ecosystem: docker
    # Look for a `Dockerfile` in the `root` directory
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
  - package-ecosystem: npm
    # Look for a `package.json` in the `/bdist/js` directory
    directory: /bdist/js
    # Check for updates once a week
    schedule:
      interval: weekly
