// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRulesRequest struct {
	Verbose              bool     `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	FixMode              bool     `protobuf:"varint,2,opt,name=fix_mode,json=fixMode,proto3" json:"fix_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRulesRequest) Reset()         { *m = ListRulesRequest{} }
func (m *ListRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRulesRequest) ProtoMessage()    {}
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *ListRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesRequest.Unmarshal(m, b)
}

func (m *ListRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesRequest.Marshal(b, m, deterministic)
}

func (m *ListRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesRequest.Merge(m, src)
}

func (m *ListRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRulesRequest.Size(m)
}

func (m *ListRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesRequest proto.InternalMessageInfo

func (m *ListRulesRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *ListRulesRequest) GetFixMode() bool {
	if m != nil {
		return m.FixMode
	}
	return false
}

type ListRulesResponse struct {
	Rules                []*ListRulesResponse_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListRulesResponse) Reset()         { *m = ListRulesResponse{} }
func (m *ListRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRulesResponse) ProtoMessage()    {}
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *ListRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesResponse.Unmarshal(m, b)
}

func (m *ListRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesResponse.Marshal(b, m, deterministic)
}

func (m *ListRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesResponse.Merge(m, src)
}

func (m *ListRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRulesResponse.Size(m)
}

func (m *ListRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesResponse proto.InternalMessageInfo

func (m *ListRulesResponse) GetRules() []*ListRulesResponse_Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type ListRulesResponse_Rule struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Purpose              string   `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRulesResponse_Rule) Reset()         { *m = ListRulesResponse_Rule{} }
func (m *ListRulesResponse_Rule) String() string { return proto.CompactTextString(m) }
func (*ListRulesResponse_Rule) ProtoMessage()    {}
func (*ListRulesResponse_Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1, 0}
}

func (m *ListRulesResponse_Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesResponse_Rule.Unmarshal(m, b)
}

func (m *ListRulesResponse_Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesResponse_Rule.Marshal(b, m, deterministic)
}

func (m *ListRulesResponse_Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesResponse_Rule.Merge(m, src)
}

func (m *ListRulesResponse_Rule) XXX_Size() int {
	return xxx_messageInfo_ListRulesResponse_Rule.Size(m)
}

func (m *ListRulesResponse_Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesResponse_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesResponse_Rule proto.InternalMessageInfo

func (m *ListRulesResponse_Rule) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListRulesResponse_Rule) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type ApplyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}

func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}

func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}

func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}

func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplyRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ApplyResponse struct {
	Failures             []*ApplyResponse_Failure `protobuf:"bytes,1,rep,name=failures,proto3" json:"failures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}

func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}

func (m *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(m, src)
}

func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}

func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetFailures() []*ApplyResponse_Failure {
	if m != nil {
		return m.Failures
	}
	return nil
}

type ApplyResponse_Position struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Line                 int32    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column               int32    `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyResponse_Position) Reset()         { *m = ApplyResponse_Position{} }
func (m *ApplyResponse_Position) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse_Position) ProtoMessage()    {}
func (*ApplyResponse_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3, 0}
}

func (m *ApplyResponse_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse_Position.Unmarshal(m, b)
}

func (m *ApplyResponse_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse_Position.Marshal(b, m, deterministic)
}

func (m *ApplyResponse_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse_Position.Merge(m, src)
}

func (m *ApplyResponse_Position) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse_Position.Size(m)
}

func (m *ApplyResponse_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse_Position.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse_Position proto.InternalMessageInfo

func (m *ApplyResponse_Position) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ApplyResponse_Position) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *ApplyResponse_Position) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type ApplyResponse_Failure struct {
	Message              string                  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Pos                  *ApplyResponse_Position `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ApplyResponse_Failure) Reset()         { *m = ApplyResponse_Failure{} }
func (m *ApplyResponse_Failure) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse_Failure) ProtoMessage()    {}
func (*ApplyResponse_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3, 1}
}

func (m *ApplyResponse_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse_Failure.Unmarshal(m, b)
}

func (m *ApplyResponse_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse_Failure.Marshal(b, m, deterministic)
}

func (m *ApplyResponse_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse_Failure.Merge(m, src)
}

func (m *ApplyResponse_Failure) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse_Failure.Size(m)
}

func (m *ApplyResponse_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse_Failure proto.InternalMessageInfo

func (m *ApplyResponse_Failure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ApplyResponse_Failure) GetPos() *ApplyResponse_Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRulesRequest)(nil), "proto.ListRulesRequest")
	proto.RegisterType((*ListRulesResponse)(nil), "proto.ListRulesResponse")
	proto.RegisterType((*ListRulesResponse_Rule)(nil), "proto.ListRulesResponse.Rule")
	proto.RegisterType((*ApplyRequest)(nil), "proto.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "proto.ApplyResponse")
	proto.RegisterType((*ApplyResponse_Position)(nil), "proto.ApplyResponse.Position")
	proto.RegisterType((*ApplyResponse_Failure)(nil), "proto.ApplyResponse.Failure")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4f, 0xea, 0x40,
	0x14, 0xc5, 0xd3, 0x42, 0xa1, 0xdc, 0xc7, 0x23, 0xef, 0x8d, 0x46, 0x6b, 0xa3, 0x09, 0xe9, 0x8a,
	0x55, 0x35, 0x65, 0xe3, 0xca, 0xc4, 0x8d, 0x6e, 0xd4, 0x98, 0xc1, 0xbd, 0x01, 0x7a, 0x8b, 0x93,
	0x94, 0xce, 0xd8, 0x69, 0x09, 0xba, 0xf6, 0xfb, 0xfa, 0x15, 0xcc, 0xfc, 0x29, 0x8a, 0xe8, 0xaa,
	0x73, 0xa6, 0xe7, 0xce, 0xf9, 0xdd, 0x7b, 0xa1, 0x2f, 0xf2, 0x7a, 0xc1, 0x8a, 0x58, 0x94, 0xbc,
	0xe2, 0xc4, 0xd3, 0x9f, 0xe8, 0x1a, 0xfe, 0xdd, 0x30, 0x59, 0xd1, 0x3a, 0x47, 0x49, 0xf1, 0xb9,
	0x46, 0x59, 0x91, 0x00, 0xba, 0x2b, 0x2c, 0x67, 0x5c, 0x62, 0xe0, 0x0c, 0x9d, 0x91, 0x4f, 0x1b,
	0x49, 0x8e, 0xc0, 0xcf, 0xd8, 0xfa, 0x71, 0xc9, 0x53, 0x0c, 0x5c, 0xf3, 0x2b, 0x63, 0xeb, 0x5b,
	0x9e, 0x62, 0xf4, 0x0a, 0xff, 0xbf, 0x3c, 0x24, 0x05, 0x2f, 0x24, 0x92, 0x31, 0x78, 0xa5, 0xba,
	0x08, 0x9c, 0x61, 0x6b, 0xf4, 0x27, 0x39, 0x31, 0xd9, 0xf1, 0x8e, 0x31, 0x56, 0x8a, 0x1a, 0x6f,
	0x78, 0x06, 0x6d, 0x25, 0xc9, 0x00, 0x5c, 0x96, 0x6a, 0x82, 0x1e, 0x75, 0x59, 0xaa, 0xb0, 0x44,
	0x5d, 0x0a, 0x85, 0xe5, 0xea, 0xcb, 0x46, 0x46, 0x09, 0xf4, 0x2f, 0x85, 0xc8, 0x5f, 0x9a, 0x06,
	0xbe, 0x57, 0x12, 0x68, 0x8b, 0x69, 0xf5, 0x64, 0xcb, 0xf4, 0x39, 0x7a, 0x77, 0xe0, 0xaf, 0x2d,
	0xb2, 0xb0, 0xe7, 0xe0, 0x67, 0x53, 0x96, 0xd7, 0xe5, 0x86, 0xf7, 0xd8, 0xf2, 0x6e, 0xf9, 0xe2,
	0x2b, 0x63, 0xa2, 0x1b, 0x77, 0x78, 0x07, 0xfe, 0x3d, 0x97, 0xac, 0x62, 0xbc, 0x20, 0x07, 0xd0,
	0xe1, 0x59, 0x26, 0xb1, 0xd2, 0xf9, 0x1e, 0xb5, 0x4a, 0x31, 0xe4, 0xac, 0x30, 0xe8, 0x1e, 0xd5,
	0x67, 0xe5, 0x9d, 0xf3, 0xbc, 0x5e, 0x16, 0x41, 0xcb, 0x78, 0x8d, 0x0a, 0x1f, 0xa0, 0x6b, 0x43,
	0x54, 0xd3, 0x4b, 0x94, 0x72, 0xba, 0x40, 0xdb, 0x4f, 0x23, 0xc9, 0x29, 0xb4, 0x04, 0x97, 0xfa,
	0xbd, 0xcf, 0xc9, 0x6e, 0x93, 0x36, 0x50, 0x54, 0x39, 0x93, 0x37, 0x07, 0x06, 0x6a, 0xb0, 0x13,
	0xac, 0x26, 0x58, 0xae, 0xd8, 0x1c, 0xc9, 0x05, 0xf4, 0x36, 0xbb, 0x20, 0x87, 0xbb, 0xdb, 0xd1,
	0xe3, 0x0c, 0x83, 0xdf, 0xd6, 0x46, 0x12, 0xf0, 0x74, 0x22, 0xd9, 0xdb, 0xce, 0x37, 0x75, 0xfb,
	0x3f, 0x41, 0xcd, 0x3a, 0xfa, 0x72, 0xfc, 0x11, 0x00, 0x00, 0xff, 0xff, 0x55, 0xfe, 0xc2, 0x62,
	0x8f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RuleSetServiceClient is the client API for RuleSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleSetServiceClient interface {
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type ruleSetServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuleSetServiceClient(cc *grpc.ClientConn) RuleSetServiceClient {
	return &ruleSetServiceClient{cc}
}

func (c *ruleSetServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, "/proto.RuleSetService/ListRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetServiceClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/proto.RuleSetService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleSetServiceServer is the server API for RuleSetService service.
type RuleSetServiceServer interface {
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
}

func RegisterRuleSetServiceServer(s *grpc.Server, srv RuleSetServiceServer) {
	s.RegisterService(&_RuleSetService_serviceDesc, srv)
}

func _RuleSetService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuleSetService/ListRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSetService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuleSetService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServiceServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuleSetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RuleSetService",
	HandlerType: (*RuleSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _RuleSetService_ListRules_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _RuleSetService_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
